// Package calc implements the deterministic engineering estimates. Every
// function is pure: explicit inputs, explicit assumptions with standard
// references, reproducible results. Nothing here is generated by an LLM,
// and every result is advisory until an authorised structural engineer has
// verified it.
//
// Scope is deliberately narrow: simple, well-understood cases (uniformly
// loaded simply supported timber beams, characteristic snow/wind loads for
// Denmark). Anything outside that scope returns an error pointing to the
// engineer instead of guessing.
package calc

import (
	"encoding/json"
	"fmt"
	"math"
	"sort"

	"github.com/balu-dk/hefai/backend/internal/domain"
)

// Assumption is one explicit premise of a calculation, with its source.
type Assumption struct {
	Text      string `json:"text"`
	Reference string `json:"reference"`
}

// Outcome is the canonical result envelope stored on calculation_estimates.
type Outcome struct {
	Method            string          `json:"method"`
	MethodVersion     string          `json:"methodVersion"`
	StandardReference string          `json:"standardReference"`
	Inputs            json.RawMessage `json:"inputs"`
	Assumptions       []Assumption    `json:"assumptions"`
	Results           map[string]any  `json:"results"`
	// Advisory is always true from this package; only an engineer review
	// flips the stored estimate to verified.
	Advisory bool   `json:"advisory"`
	Notice   string `json:"notice"`
}

const advisoryNotice = "Vejledende overslag beregnet af Hefai. Skal kontrolleres og godkendes af en " +
	"autoriseret/anerkendt statiker før brug i konstruktion eller myndighedsprojekt."

// Runner executes one named method on raw JSON inputs.
type Runner func(inputs json.RawMessage) (*Outcome, error)

// Registry maps method names to their implementations. Method names are
// stored on estimates, so they are part of the persisted contract —
// breaking changes require a new versioned name.
var Registry = map[string]Runner{
	"snow_load_dk_v1":    runSnowLoad,
	"wind_load_dk_v1":    runWindLoad,
	"timber_beam_udl_v1": runTimberBeam,
}

// MethodInfo documents a method for the API.
type MethodInfo struct {
	Name              string `json:"name"`
	Description       string `json:"description"`
	StandardReference string `json:"standardReference"`
	InputsExample     any    `json:"inputsExample"`
}

func Methods() []MethodInfo {
	methods := []MethodInfo{
		{
			Name:              "snow_load_dk_v1",
			Description:       "Karakteristisk snelast på tag i Danmark ud fra taghældning.",
			StandardReference: "DS/EN 1991-1-3 + DK NA",
			InputsExample:     SnowLoadInput{RoofAngleDeg: 25},
		},
		{
			Name:              "wind_load_dk_v1",
			Description:       "Peak-hastighedstryk (vindlast) ud fra basisvindhastighed, terrænkategori og højde.",
			StandardReference: "DS/EN 1991-1-4 + DK NA",
			InputsExample:     WindLoadInput{HeightM: 6, TerrainCategory: "II", NearWestCoast: false},
		},
		{
			Name:              "timber_beam_udl_v1",
			Description:       "Simpelt understøttet træbjælke med jævnt fordelt last: bøjning, forskydning, nedbøjning.",
			StandardReference: "DS/EN 1995-1-1 (Eurocode 5) + DK NA, lastkombination efter DS/EN 1990 DK NA",
			InputsExample: TimberBeamInput{
				SpanM: 4.0, SpacingM: 0.6, PermanentLoadKNM2: 0.5, VariableLoadKNM2: 2.0,
				TimberClass: "C24", WidthMM: 45, HeightMM: 195,
			},
		},
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })
	return methods
}

// Run executes a method by name.
func Run(method string, inputs json.RawMessage) (*Outcome, error) {
	runner, ok := Registry[method]
	if !ok {
		return nil, domain.Validation(fmt.Sprintf("ukendt beregningsmetode %q — se /calc/methods", method))
	}
	return runner(inputs)
}

func decodeInputs[T any](raw json.RawMessage, into *T) error {
	if len(raw) == 0 {
		return domain.Validation("inputs mangler")
	}
	if err := json.Unmarshal(raw, into); err != nil {
		return domain.Validation("ugyldige inputs: " + err.Error())
	}
	return nil
}

func round(v float64, decimals int) float64 {
	scale := math.Pow(10, float64(decimals))
	return math.Round(v*scale) / scale
}
